title: Chirag Byanjankar
logo: assets/fe88cfcf-c1db-48bc-9ab3-8519a4d8b9f1.jpg
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal

show_ref_links: true
cvlocation: /assets/Byanjankar_Resumme.pdf
email: cbyanjankar99@gmail.com
scholar: https://scholar.google.com/citations?hl=en&view_op=list_works&authuser=1&gmla=AL3_zijUMq13pozwqGXA9GxriajNxuEzXIdCzbyGhHfyd9IUbYvB9-6ifjXKk0IfXgiz1MgsL-BpMk11nttiVA&user=knPdFO0AAAAJ
linkedin: https://www.linkedin.com/in/chirag-byanjankar/
